language: node_js
node_js:
  - "stable"
script:
  - npm install
  - npm rebuild node-sass
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  on:
    branch: legacy